version: "3"
services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./server:/usr/share/nginx/html:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/:/etc/nginx/conf.d:ro
        restart: unless-stopped

